"""Emit runnable HTTPie commands from the IR.

Design notes on correctness:

* Every value that comes from the spec is passed through :func:`shlex.quote`,
  so arbitrary example data can never break out of its argument or be
  re-interpreted by the shell.
* Secrets (tokens, passwords, API keys) are emitted as ``$ENV`` references that
  are deliberately *double*-quoted and NOT run through ``shlex.quote`` — they
  must be expanded by the shell. Their defaults are declared in a header block.
* A JSON object body is emitted as editable HTTPie request items
  (``key=`` / ``key:=``); anything else, or an object with awkward keys, falls
  back to ``--raw`` (HTTPie forbids mixing ``--raw`` with request items).
"""

from __future__ import annotations

import json
import re
import shlex
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import quote

from ..model import ApiModel, Body, Request, SecurityScheme

# A request-item / query / header token whose *name* is "simple" can be emitted
# directly; otherwise we escape or fall back to --raw.
_SIMPLE_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_.\-]*$")


@dataclass
class HttpieOptions:
    command: str = "http"          # or "https"
    base_url: Optional[str] = None  # overrides the spec's server as BASE_URL default
    offline: bool = False           # add --offline (build & print, don't send)
    multiline: bool = True          # wrap long commands with backslash-newlines
    include_auth: bool = True
    include_optional: bool = False  # informational; extraction already applied it
    # --ignore-stdin makes commands safe to run non-interactively (in a script,
    # or piped) — without it HTTPie errors when data items meet a non-TTY stdin.
    ignore_stdin: bool = True


@dataclass
class _EnvVar:
    name: str
    default: str
    comment: str


@dataclass
class _ScriptState:
    env: Dict[str, _EnvVar] = field(default_factory=dict)

    def add(self, var: _EnvVar) -> None:
        # First declaration wins; keeps a stable, de-duplicated header.
        self.env.setdefault(var.name, var)


def env_name(raw: str) -> str:
    """Turn an arbitrary identifier into a safe shell variable name."""
    name = re.sub(r"[^A-Za-z0-9]+", "_", raw).strip("_").upper()
    if not name:
        name = "VALUE"
    if name[0].isdigit():
        name = "_" + name
    return name


class HttpieEmitter:
    def __init__(self, options: Optional[HttpieOptions] = None) -> None:
        self.opt = options or HttpieOptions()

    # -- public ------------------------------------------------------------

    def render_script(self, model: ApiModel) -> str:
        """Render the whole API as one runnable bash script."""
        state = _ScriptState()
        base_default = self.opt.base_url or model.primary_server or "https://api.example.com"
        state.add(_EnvVar("BASE_URL", base_default, "API base URL"))

        blocks: List[str] = []
        for req in model.requests:
            blocks.append(self._render_one(req, state))

        header = self._script_header(model, state)
        return header + "\n\n" + "\n\n".join(blocks) + "\n"

    def render_commands(self, model: ApiModel) -> List[Tuple[str, str]]:
        """Return ``(label, command)`` pairs, one per operation (no env header)."""
        out = []
        for req in model.requests:
            state = _ScriptState()
            cmd = self._command(req, state)
            out.append((req.label, cmd))
        return out

    # -- script scaffolding -----------------------------------------------

    def _script_header(self, model: ApiModel, state: _ScriptState) -> str:
        lines = [
            "#!/usr/bin/env bash",
            f"# {model.title} {model.version}".rstrip(),
            "# Generated by openapi2httpie — https://github.com/AlexDevFlow/openapi2httpie",
            "#",
            "# Edit the variables below (or export them beforehand), then run this file.",
            "# Each request is an independent, copy-pasteable HTTPie command.",
            "",
        ]
        for var in state.env.values():
            comment = f"  # {var.comment}" if var.comment else ""
            lines.append(f': "${{{var.name}:={var.default}}}"{comment}')
        return "\n".join(lines)

    # -- one request -------------------------------------------------------

    def _render_one(self, req: Request, state: _ScriptState) -> str:
        comment_lines = [f"# {req.method} {req.path}"]
        if req.summary:
            comment_lines.append(f"# {req.summary}")
        if req.deprecated:
            comment_lines.append("# DEPRECATED")
        command = self._command(req, state)
        return "\n".join(comment_lines) + "\n" + command

    def _command(self, req: Request, state: _ScriptState) -> str:
        # ``head`` is everything up to and including the URL and stays on the
        # first line; ``items`` are the request items, wrapped one-per-line when
        # the command is long.
        head: List[str] = [self.opt.command]
        if self.opt.ignore_stdin:
            head.append("--ignore-stdin")
        if self.opt.offline:
            head.append("--offline")

        raw_items: List[str] = []
        if self.opt.include_auth and req.security:
            opts, items = self._auth(req.security[0], state)
            head.extend(opts)
            raw_items.extend(items)

        # Body flags (e.g. --form, --multipart, Content-Type) precede the URL.
        body_flags, body_items, body_raw = self._body(req.body, state)
        head.extend(body_flags)

        head.append(req.method)
        head.append(_dq(self._url(req, state)))

        items: List[str] = []
        for q in req.query_params:
            items.append(shlex.quote(f"{q.name}=={_stringify(q.value)}"))
        for h in req.header_params:
            items.append(shlex.quote(f"{h.name}:{_stringify(h.value)}"))
        items.extend(raw_items)
        items.extend(body_items)
        if body_raw is not None:
            items.append(body_raw)

        return self._join(head, items)

    def _join(self, head: List[str], items: List[str]) -> str:
        parts = head + items
        one_line = " ".join(parts)
        if not self.opt.multiline or not items or len(one_line) <= 100:
            return one_line
        return " ".join(head) + " \\\n    " + " \\\n    ".join(items)

    # -- URL ---------------------------------------------------------------

    def _url(self, req: Request, state: _ScriptState) -> str:
        path = req.path if req.path.startswith("/") else "/" + req.path
        for pp in req.path_params:
            value = _stringify(pp.value) or pp.name
            path = path.replace("{" + pp.name + "}", quote(value, safe=""))
        return "$BASE_URL" + path

    # -- auth --------------------------------------------------------------

    def _auth(self, schemes: List[SecurityScheme], state: _ScriptState) -> Tuple[List[str], List[str]]:
        """Return ``(options, items)`` for the first applicable requirement."""
        options: List[str] = []
        items: List[str] = []
        for sc in schemes:
            if sc.kind == "basic":
                state.add(_EnvVar("USERNAME", "REPLACE_ME", "basic-auth username"))
                state.add(_EnvVar("PASSWORD", "REPLACE_ME", "basic-auth password"))
                options.extend(["-a", '"$USERNAME:$PASSWORD"'])
            elif sc.kind in ("bearer", "oauth2", "openIdConnect"):
                state.add(_EnvVar("TOKEN", "REPLACE_ME", f"{sc.kind} token"))
                options.extend(["-A", "bearer", "-a", '"$TOKEN"'])
            elif sc.kind == "apiKey":
                var = env_name(sc.param_name or sc.name or "api_key")
                state.add(_EnvVar(var, "REPLACE_ME", f"API key ({sc.param_name} in {sc.location})"))
                pname = sc.param_name or "X-API-Key"
                if sc.location == "query":
                    items.append(f'"{pname}==${var}"')
                elif sc.location == "cookie":
                    items.append(f'"Cookie:{pname}=${var}"')
                else:  # header (default)
                    items.append(f'"{pname}:${var}"')
        return options, items

    # -- body --------------------------------------------------------------

    def _body(self, body: Body, state: _ScriptState) -> Tuple[List[str], List[str], Optional[str]]:
        """Return ``(flags, items, raw_arg)``."""
        if body.kind == "none":
            return [], [], None

        if body.kind == "json":
            if isinstance(body.value, dict) and self._keys_simple(body.value):
                return [], self._json_items(body.value), None
            raw = _compact_json(body.value)
            return [], [], f"--raw={shlex.quote(raw)}"

        if body.kind == "raw":
            raw = body.raw or ""
            items = []
            # Non-JSON raw bodies need their content type stated explicitly. This
            # is a header *item* (after the URL), not a pre-method flag.
            if body.content_type and "json" not in body.content_type.lower():
                items.append(shlex.quote(f"Content-Type:{body.content_type}"))
            return [], items, f"--raw={shlex.quote(raw)}"

        if body.kind == "form":
            items = [shlex.quote(f"{k}={_stringify(v)}") for k, v in (body.value or {}).items()]
            return ["--form"], items, None

        if body.kind == "multipart":
            items: List[str] = []
            for k, v in (body.value or {}).items():
                if k in body.file_fields:
                    items.append(shlex.quote(f"{k}@./path/to/{k}"))
                else:
                    items.append(shlex.quote(f"{k}={_stringify(v)}"))
            return ["--multipart"], items, None

        return [], [], None

    @staticmethod
    def _keys_simple(obj: Dict[str, Any]) -> bool:
        return all(isinstance(k, str) and _SIMPLE_KEY.match(k) for k in obj.keys())

    @staticmethod
    def _json_items(obj: Dict[str, Any]) -> List[str]:
        items: List[str] = []
        for key, value in obj.items():
            if isinstance(value, str):
                items.append(shlex.quote(f"{key}={value}"))
            else:
                items.append(shlex.quote(f"{key}:={_compact_json(value)}"))
        return items


def _compact_json(value: Any) -> str:
    """Serialise a value to compact JSON, coercing any exotic scalar to str."""
    return json.dumps(value, default=str, separators=(",", ":"))


def _dq(value: str) -> str:
    """Double-quote a token so ``$VAR`` references expand."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`")
    return f'"{escaped}"'


def _stringify(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, (dict, list)):
        return _compact_json(value)
    return str(value)
